# Generated by Django 3.0.5 on 2020-05-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=120)),
                ('invoice', models.CharField(max_length=80)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='expenses.Expense')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='wallets.Wallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
