# Generated by Django 3.0.5 on 2020-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug_name', models.SlugField(help_text="Para el Banco de Bogotá: 'bogota' o 'bancobogota'", unique=True)),
                ('description', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
