# Generated by Django 3.0.5 on 2020-05-11 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Ingrese el número de documento sin caracteres especiales. Maximo once caracteres.', regex='\\d{1,11}$')]),
        ),
    ]
