# Generated by Django 3.0.5 on 2020-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug_name', models.SlugField(unique=True)),
                ('detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug_name', models.SlugField(unique=True)),
                ('detail', models.CharField(max_length=300)),
                ('groups', models.ManyToManyField(to='expenses.Group')),
            ],
        ),
    ]
